### ISSUE TITLE
need inline attribute for alternative references

### ISSUE THREAD

**Issue by bterlson** [jmdyck/es-spec-emu#12]
Somewhat related to #11, emu wants an inline attribute on alternative references, eg. in clauses that define semantics for a production.

**Comment by jmdyck** [comment]
Are you talking about the `a` attribute of `<emu-prodref>`?

**Comment by bterlson** [comment]
Yep!

**Comment by bterlson** [comment]
Possibly wasn't clear before - this is mainly about adding `class=inline` to emu-production (or if you take #11 first, emu-prodref). Would be awesome to get this this week as it impacts readability of the draft.

**Comment by jmdyck** [comment]
> this is mainly about adding `class=inline` to emu-production

Ah! Okay.

Well, currently, es-spec.emu doesn't use `<emu-production>` at all. Could `<emu-grammar>` take `class=inline` instead?

(I could maybe do #11 first, but it would be good to get responses to my last three comments there.)

**Comment by bterlson** [comment]
Emu-grammar can take inline as well IIRC.

Sorry will look at comments on #11!

**Comment by jmdyck** [comment]
Okay, I've added `class=inline` to (what I assume are) appropriate `<emu-grammar>` elements (e.g., in 7.1.3.1.1, 11.8.3.1,  and 21.2.2.*), which improves appearances when using ecmarkup's elements.css.

**Comment by bterlson** [comment]
Need it also in productions that define semantics for productions, eg. those here: http://tc39.github.io/ecma262/#sec-generator-function-definitions-static-semantics-early-errors

**Comment by jmdyck** [comment]
I'm assuming you don't want `class="inline"` in every such case, as that would cause ecmarkup+elements.css to poorly render multi-production blocks and multi-rhs productions. (See [14.6.2.1 Statement Rules](http://www.ecma-international.org/ecma-262/6.0/#sec-statement-rules) for examples of both.)

What I've done (I think) is add the attribute to every production that is rendered as a single line in the ES6 spec.

However, note that this still leads to poor rendering. E.g. in 14.6.2.1, the productions for FunctionStatementList and StatementListItem will run together. Similarly for Block and ReturnStatement and LabelledItem. It seems to me you need another value for `class`, one that gives the element `display:block` (to prevent the run-together), but that allows the production to render as a single line.

Mind you, I think adding `class="inline"` (or whatever) to `<emu-grammar>` _in the emu source_ is the wrong approach. Instead, ecmarkup should generate the necessary attributes based on whether productions are single-line or multi-line in the source. (I.e., the ecmarkup code should be able to ask the grammarkdown code how a given production was formatted.)

**Comment by bterlson** [comment]
I think having two forms is easier to deal with than adding another class value personally. What is wrong with doing what I do with async functions and putting <br> between productions in multiple-production blocks? 

All the multi-RHS blocks are not inline afaict. Do you have a counter example I'm not seeing?

Agree that emu-grammar should be able to emit inline on emu-production based on the input source (and, if you agree, emit <br> between multiple inline productions).

**Comment by jmdyck** [comment]
> I think having two forms is easier to deal with than adding another class value personally. What is wrong with doing what I do with async functions and putting `<br>` between productions in multiple-production blocks?

Objectively, you may find it harder to achieve consistent styling (e.g., the spacing between productions in a multi-production block) in a cross-browser way.

Subjectively, it feels wrong to me because you'd be telling CSS to generate a bunch of inline-boxes (which are odd in a block formatting context), when the layout you want is actually that of block-boxes (which are normal for a block formatting context). Inserting `<br>` elements into the HTML feels like a kludge. Not that I'm above kludges, but it seems like a non-kludgey solution wouldn't be that hard.

> All the multi-RHS blocks are not inline afaict. Do you have a counter example I'm not seeing?

No, I should have said "still leads to some poor rendering, though not as much". Multi-RHS productions should be okay, and some multi-production blocks are okay, but some aren't.

> Agree that emu-grammar should be able to emit inline on emu-production based on the input source (and, if you agree, emit `<br>` between multiple inline productions).

Heck, I don't think you need my agreement. Emitting `<br>`s is probably an easy change that will more-or-less fix some rendering glitches. But down the road, you might want a different solution. (I think I'm more interested in ecmarkup's input than its output, anyhow.)

**Comment by bterlson** [comment]
> Subjectively, it feels wrong to me because you'd be telling CSS to generate a bunch of inline-boxes (which are odd in a block formatting context), when the layout you want is actually that of block-boxes (which are normal for a block formatting context).

I don't think inside a p tag (as the async functions spec does it) is a block formatting context.

But maybe part of the problem is I can't see a reasonable alternative that is easy to explain to people. How would you do it?

> Heck, I don't think you need my agreement. 

Of course not, but that doesn't mean I can't defer to your judgement if I like, right??

**Comment by bterlson** [comment]
emu-production class=inline for productions in text, class=collapsed for productions whose RHS you want to render on the same line as its LHS, and no class for default behavior.

emu-grammar class=inline for productions in text, no class for default behavior. Grammarkdown emits emu-production class=collapsed if the input text is collapsed. (though as a stopgap emu-grammar class="collapsed" can probably be styled appropriately)

Does this seem rational?

**Comment by jmdyck** [comment]
> Subjectively, it feels wrong to me because you'd be telling CSS to generate a bunch of inline-boxes (which are odd in a block formatting context), when the layout you want is actually that of block-boxes (which are normal for a block formatting context).
> 
> I don't think inside a p tag (as the async functions spec does it) is a block formatting context.

(Sorry, it was late, and it didn't immediately occur to me where to find "async functions".)

You're right, a `<p>` element doesn't generate a block formatting context (assuming the CSS doesn't make it so). But that makes it even odder, because then you've got a collection of block-like things (actual block-boxes, and/or inline-boxes that you'd like presented in a block-like way), and you're putting them into an _inline_ formatting context.

> But maybe part of the problem is I can't see a reasonable alternative that is easy to explain to people. How would you do it?

The phrase "easy to explain to people" sounds like you're talking about explaining the emu format to proposal authors, as distinct from the HTML markup that ecmarkup generates. So from that point of view, I would tell people...

`<emu-grammar>` can appear:
- embedded in a sentence (e.g. "The MV of ..."), or
- as a 'top-level' item in an emu-clause/emu-annex (e.g., in a "Syntax" section, or as the "head" of an algorithm in a syntax-discriminated operation), or
- miscellaneous other block-level constructs (e.g., emu-note).

Based on the context and content of the emu-grammar element, ecmarkup can generate markup that "does the right thing" in terms of formatting, so you shouldn't need to add anything like `class` or `style` attributes, or `<br>` tags. [And then some input/output examples, which might obviate the parenthetical examples above.]

And similarly for `<emu-prodref>`.

[As for `<emu-production>`, I'm not sure why an emu doc would ever use one, so I don't think of them as something that needs to be explained to authors.]

**Comment by jmdyck** [comment]
> emu-production class=inline [...], class=collapsed [...]
> 
> emu-grammar class=inline [...]
> 
> Does this seem rational?

Yup, seems fairly rational. (I don't think emu-grammar needs style-related attributes, so it's not optimal from that POV, but it's rational nonetheless.)

**Comment by bterlson** [comment]
> You're right, a  <p>  element doesn't generate a block formatting context (assuming the CSS doesn't make it so). But that makes it even odder, because then you've got a collection of block-like things (actual block-boxes, and/or inline-boxes that you'd like presented in a block-like way), and you're putting them into an inline formatting context.

This seems no more odd than putting <br> after consecutive images. This is very common.

> [As for  <emu-production> , I'm not sure why an emu doc would ever use one, so I don't think of them as something that needs to be explained to authors.]

it needs to be rationalized as its what Grammarkdown would emit.

To me keying off of context is unlikely to be very nice. Specifically I doubt it would be possible to emit markup that will give the author the styles they want in all cases.

**Comment by jmdyck** [comment]
> You're right, a br element doesn't generate a block formatting context (assuming the CSS doesn't make it so). But that makes it even odder, because then you've got a collection of block-like things (actual block-boxes, and/or inline-boxes that you'd like presented in a block-like way), and you're putting them into an inline formatting context.
> 
> This seems no more odd than putting br after consecutive images. This is very common.

That's a fairly different example though, because HTML img elements generate inline-level boxes, so putting them in an inline formatting context makes sense, and there aren't block-level boxes complicating things.

> To me keying off of context is unlikely to be very nice. Specifically I doubt it would be possible to emit markup that will give the author the styles they want in all cases.

Are they likely to want styles that don't occur in the ES6 spec? Because keying off of context + content seemed to suffice for that.

(And then there's the question of whether a proposal's author should always get the styles they want, since presumably you want a spec that's stylistically fairly consistent.)

**Comment by bterlson** [comment]
Trying to understand what you're advocating here... we would still have a collapsed attribute in your world (which is ideally emitted by grammarkdown), and then have a heuristic for determining if an emu-production should be inline or block depending on context. I guess if emu-production parent is emu-clause or body then block, otherwise inline?

**Comment by bterlson** [comment]
@jmdyck can we continue to iterate on the open issues in this repo?

**Comment by jmdyck** [comment]
> @jmdyck can we continue to iterate on the open issues in this repo?

I guess so, if that's what you'd prefer.

**Comment by bterlson** [comment]
I think this can be closed now. As of latest emu, there's a heuristic in place: if a production is NOT a direct child of emu-clause-alikes, then it has class=inline. If a production has a collapsed attribute or it is defined in an emu-grammar block where all productions are collapsed, then the emu-production will have a collapsed attribute.

**Comment by jmdyck** [comment]
I agree, emu-grammar no longer needs class="inline" (in the input doc, anyhow), so I'm closing this issue.

(I have concerns/suggestions re other things in this area, but it makes sense to raise them elsewhere.)
